# Generated by Django 5.0.4 on 2024-04-24 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('department', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'student',
            },
        ),
    ]
